global:
  scrape_interval: 5s
  evaluation_interval: 5s

# Load alert rules
rule_files:
  - '/etc/prometheus/alerts/*.yml'

scrape_configs:
  - job_name: 'triton'
    static_configs:
      - targets: ['triton-api:8002']
        labels:
          group: 'triton_inference_server'

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          group: 'system'

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
